# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Agencia N1
email: cbsorrilha@hotmail.com
links: [{"ref":"#", "title":"html"}, {"ref":"#", "title":"css"}, {"ref":"#", "title":"javascript"}, {"ref":"#", "title":"sass"}, {"ref":"#", "title":"grunt"}]
description: > # Teste para agência N1
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  cbsorrilha
exclude: ["node_modules", "bower_components", "_psd", "_app", "gulpfile.js", "package.json", "README.MD"]

# Build settings
markdown: kramdown
